# The numpy library

numpy is an abbreviation for the **num**eric **py**thon library. It is a library that is based upon a main data structure:

* the ```ndarray``` class

The ```ndarray``` class is a numeric datastructure similar to a Python ```list``` but unlike a Python ```list``` broadcasts numeric operators and mathematical functions. 

```numpy``` is the most commonly used third-party Python library. It is fundamental for other popular data science libraries:

* The Python and Data Analysis Library - ```pandas```
* The Matrix Plotting Library - ```matplotlib```
* The Data Visualization Library - ```seaborn``` 

These libraries are based upon ```numpy``` and are collectively known as the ```numpy``` stack.

## Tuples and Lists

The ```list``` is a ```builtins``` collection that can be used to store numeric data:

In [2]:
nums1 = [1, 2, 3, 4, 5]
nums2 = [2, 4, 6, 8, 10]

However operators are setup for collections and the ```+``` operator for example performs concatenation, instead of addition:

In [3]:
nums1 + nums2

[1, 2, 3, 4, 5, 2, 4, 6, 8, 10]

Numeric addition and other mathematical operations can be broadcast along an inbuilt array using a ```for``` loop:

In [4]:
summed = []

for idx in range(len(nums1)):
    summed.append(nums1[idx] + nums2[idx])

print(summed)

[3, 6, 9, 12, 15]


Or a slightly more elegant list comprehension:

In [5]:
[num1 + num2 for num1, num2 in zip(nums1, nums2)]

[3, 6, 9, 12, 15]

## Array Module

The ```tuple``` and ```list``` collections are very versatile and each record can be a Python ```object``` from a different class:

This versatility however becomes disadvantagous when the intent is to work with only numeric data using a ```for``` loop as seen above. 

Having the wrong datatype for an element will result in a ```TypeError```.

Python has an ```array``` module. It can be imported using:

In [6]:
import array

The ```array``` module has the following identifiers:

In [7]:
dir(array)

['ArrayType',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_array_reconstructor',
 'array',
 'typecodes']

The two main identifiers are the attribute ```typecodes```:

In [8]:
array.typecodes

'bBuhHiIlLqQfd'

And the ```array``` class which can be used to create an ```array``` of a uniform datatype:

In [9]:
array.array?

Init signature: array.array(self, /, *args, **kwargs)
Docstring:     
array(typecode [, initializer]) -> array

Return a new array whose items are restricted by typecode, and
initialized from the optional initializer value, which must be a list,
string or iterable over elements of the appropriate type.

Arrays represent basic values and behave very much like lists, except
the type of objects stored in them is constrained. The type is specified
at object creation time by using a type code, which is a single character.
The following type codes are defined:

    Type code   C Type             Minimum size in bytes
    'b'         signed integer     1
    'B'         unsigned integer   1
    'u'         Unicode character  2 (see note)
    'h'         signed integer     2
    'H'         unsigned integer   2
    'i'         signed integer     2
    'I'         unsigned integer   2
    'l'         signed integer     4
    'L'         unsigned integer   4
    'q'         signed integer     8 

For example the type code ```'l'``` can be used to create an array where each element is a 4 byte signed integer:

In [10]:
nums1 = array.array('l', [1, 2, 3, 4, 5])
nums2 = array.array('l', [2, 4, 6, 8, 10])

In [11]:
nums1

array('l', [1, 2, 3, 4, 5])

In [12]:
nums2

array('l', [2, 4, 6, 8, 10])

The ```array``` instance otherwise behaves consistently to a ```list``` and the ```+``` operator performs concatenation:

In [13]:
nums1 + nums2

array('l', [1, 2, 3, 4, 5, 2, 4, 6, 8, 10])

```list``` comprehension can be used for addition:

In [14]:
array.array('l', [num1 + num2 for num1, num2 in zip(nums1, nums2)])

array('l', [3, 6, 9, 12, 15])

It is possible to use other type codes to conserve memory however this comes at the expense of dynamic range. The type code ```'B'``` for example corresponds to an unsigned 1 byte integer. This means it has the maximum value: 

In [15]:
2 ** (1 * 8) # 1 byte

256

In [16]:
2 ** (2 * 8) # 2 bytes

65536

In [17]:
2 ** (4 * 8) # 4 bytes

4294967296

Recall Python uses zero order indexing so this is ```0:256``` inclusive of the lower bound and exclusive of the upper bound.

The type code ```'b'``` corresponds to a signed 1 byte integer which means half of these values must correspond to negative numbers and the other half of the values correspond to positive numbers. So this is ```-128:128``` inclusive of the lower bound and exclusive of the upper bound.

The type code ```'d'``` can be used to create an array where each element is a 8 byte floating point number:

In [18]:
nums3 = array.array('d', [0.1, 0.2, 0.3, 0.4, 0.5])
nums4 = array.array('d', [0.2, 0.4, 0.6, 0.8, 1.0])

In [19]:
nums3

array('d', [0.1, 0.2, 0.3, 0.4, 0.5])

In [20]:
nums4

array('d', [0.2, 0.4, 0.6, 0.8, 1.0])

Each ```float``` in this array behaves consistently to a ```float``` and is displayed in decimal but encoded in binary. Therefore the recursive rounding errors encountered previously when the ```float``` class was examined still apply:

In [21]:
array.array('d', [num3 + num4 for num3, num4 in zip(nums3, nums4)])

array('d', [0.30000000000000004, 0.6000000000000001, 0.8999999999999999, 1.2000000000000002, 1.5])

The datatype can be changed to ```'f'``` from ```'d'``` which halves the precision which can be seen by a reduction in the trailing zeros:

In [22]:
array.array('f', [num3 + num4 for num3, num4 in zip(nums3, nums4)])

array('f', [0.30000001192092896, 0.6000000238418579, 0.8999999761581421, 1.2000000476837158, 1.5])

Note the ```float``` in ```builtins``` uses ```'d'``` by default which is why this lower precision ```'f'``` is displayed in the above with the precision of ```'d'```. The values past the specified precision are meaningless.

## Dimensions

In mathematics, a matrix has rows and columns:

$$ \begin{bmatrix} 
   1 & 2 & 3 \\
   4 & 5 & 6 \\
   7 & 8 & 9 \\
   \end{bmatrix} $$

By definition "a row" consists of 1 row by n (in this case 3) columns:

$$\begin{bmatrix}1&2&3\end{bmatrix}$$

By definition "a column" consists of multiple rows (in this case 3) by 1 column:

$$  \begin{bmatrix}
    1 \\
    4 \\
    7 \\
    \end{bmatrix} $$ 

The ```array```, ```list``` and ```tuple``` are 1 dimensional collections. These are normally represented as a row:

In [23]:
nums = array.array('l', [1, 2, 3])

In [24]:
nums

array('l', [1, 2, 3])

In [33]:
len(nums)

3

If they are input as a column then nothing changes:

In [28]:
nums = array.array('l', [1, 
                         4, 
                         7])

The default representation returned shows that the array is still represented as a row:

In [29]:
nums

array('l', [1, 4, 7])

In [32]:
len(nums)

3

Strictly the ```array``` instance is neither a row nor or a column but is a collection that has a single dimension with a length of ```3```.

Each element in an ```array``` instance is a fixed fundamental datatype however a ```list``` or ```tuple``` can contain other collections.

$$ \begin{bmatrix} 
   1 & 2 & 3 \\
   4 & 5 & 6 \\
   7 & 8 & 9 \\
   \end{bmatrix} $$

Each row in the matrix can be represented as a 3-element ```tuple```:

In [34]:
row0 = (1, 2, 3)
row1 = (4, 5, 6)
row2 = (7, 8, 9)

And each of these ```tuple``` rows can be an element in a ```list```:

In [35]:
[row0, 
 row1, 
 row2]

[(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In the above the different brackets for the 2 collections are used to clearly distinguish rows and columns. The ```,``` delimiter in the ```tuple``` is an instruction to move onto a new row and the ```,``` delimiter in the ```list``` is an instruction to move onto a new column. 

It is more typicaly to use a ```list``` of nested ```list``` instances. It can be spaced out as a matrix for clarity but the default representation will show a flattened format:

In [38]:
nums = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]

Notice now that the outer list is indexed into to get a row:

In [43]:
nums[0]

[1, 2, 3]

Then this row (inner list) is indexed into to get the column:

In [44]:
nums[0][1]

2

This means that a nested for loop needs to be used to perform numeric addition for example of the scalar ```1``` to this matrix and the syntax therefore becomes quite cumbersome:

In [45]:
outer = []

for row in nums:
    inner = []
    for num in row:
        inner.append(num + 1) 
    outer.append(inner)
    
outer

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

## ndarray

The numeric Python library is based upon the n-dimensional array ```ndarray``` data structure. The ```ndarray``` unlike the ```array``` data structure can be scaled to other dimensions. 

The ```ndarray``` is also mutable and unlike the other collections has datamodel identifiers configured for numeric operations, making it much simpler to broadcast a numerical operation along a ```ndarray``` using a cleaner syntax without the use of for loops or list comprehensions. 

In addition to numeric data model methods the ```numpy``` library also provides equivalents to range objects, mathematical functions, statistics, datetimes and random number generation that can all be broadcast along the ```ndarray```. Previous tutorials have established how these features are used over a single value known as a scalar by use of ```builtins``` or another Python standard module. 

Once the mechanics of using a ```ndarray``` are setup, such as indexing and working across multiple dimensions, this previous knowledge can easily be applied and it becomes a case of using the equivalent ```numpy``` library function or ```ndarray``` method.


## Importing numpy

```numpy``` is a third-party Python library. It is preinstalled in the Anaconda base Python environment of the Anaconda Python distribution but is not preinstalled with Python.

Because the ```numpy``` library is so commonly used, it is typically imported using a 2 letter abbreviation ```np```. The ```numpy``` library includes a large number of functions and it is more convenient to access these using this two letter abbreviation:

In [46]:
import numpy as np

If the Python environment is setup correctly the line of code above should run without any errors. However when ```numpy``` is attempted to be imported from a Python environment without ```numpy``` a ```ModuleNotFoundError``` will display. In this scenario see eacrlier tutorials on setting up Anaconda.

Once imported, the module datamodel attributes ```__name__``` (*dunder name*), ```__version__``` (*dunder version*) and ```__path__``` (*dunder path*) can be examined:

In [47]:
np.__name__

'numpy'

In [48]:
np.__version__

'1.26.0'

In [49]:
np.__path__

['c:\\Users\\pyip\\miniconda3\\envs\\jupyterlab\\Lib\\site-packages\\numpy']

Once imported a large number of identifiers will be listed by inputting:

## ndarray factory functions


The n-dimensional array ```ndarray``` class is the data structure the ```numpy``` library is based around:

In [50]:
np.ndarray?

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

The docstring states: arrays should be constructed using the ```array``` factory function.

The docstring outlines some import parameters for array creation:

|parameter|description|
|---|---|
|shape|tuple of ints representing the shape of the created array.|
|dtype|data-type, optional object that can be interpreted as a numpy data type.|
|order|{'C', 'F'}, optional Row-major (C-style) or column-major (Fortran-style) order.|

Aswell as some important attributes of an ```ndarray```:

|attribute|description|
|---|---|
|size|int number of elements in the array|
|ndim|int number of dimensions of the array|
|shape|tuple of ints representing the shape of the array.|
|T|transpose of the array.|
|flat|flattened version of the array as an iterator.|
|real|real part of the array.|
|imag|imaginary part of the array.|
|data|the elements array in memory.|
|itemsize|the memory use of each array element in bytes.|
|nbytes|the total number of bytes required to store the array data, data * itemsize|

The following matrix:

$$ \begin{bmatrix} 
   1 & 2 & 3 \\
   4 & 5 & 6 \\
   7 & 8 & 9 \\
   \end{bmatrix} $$

Has 3 rows by 3 columns; a ```shape``` of ```(3, 3)```.

All of these values have the datatype ```dtype``` of ```int```.

The buffer can be supplied using a ```list``` of ```list``` instances supplied to the function ```np.array```:

In [66]:
np.ndarray(shape=(3, 3), 
           dtype=int, 
           buffer=np.array([[1, 2, 3], 
                            [4, 5, 6], 
                            [7, 8, 9]]))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

The factory function ```np.array``` is usually used directly:

In [69]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

If only ```object``` is supplied to the ```np.array``` factory function, the ```dtype``` and the ```ndmin``` are implied from the datatype of the elements in the ```list``` (or ```list``` of nested ```list``` instances):

|parameter|description|
|---|---|
|object|any (nested) sequence, usually a list.|
|dtype|data-type, optional object that can be interpreted as a numpy data type.|
|copy|if true (default), then the object is copied.|
|ndmin|specifies the minimum number of dimensions that the resulting array should have. Ones will be prepended to the shape to satisfy this requirement|

If the ```object``` supplied is a ```list``` a 1d ```ndarray``` instance will be instantiated:

In [123]:
one_d = np.array(object=[1, 2, 3])

In [124]:
one_d

array([1, 2, 3])

In [125]:
one_d.dtype

dtype('int32')

In [126]:
one_d.ndim

1

In [127]:
one_d.shape

(3,)

If the ```object``` is a ```list``` of nested ```list``` instances a 2d ```ndarray``` will be instantiated:

In [93]:
mat = np.array(object=[[1, 2, 3], 
                       [4, 5, 6], 
                       [7, 8, 9]])

In [94]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
mat.dtype

dtype('int32')

In [96]:
mat.ndim

2

In [97]:
mat.shape

(3, 3)

Normally the ```object``` is supplied positionally and the other keyword arguments are only supplied when they differ from the defaults. For example ```ndmin``` can be assigned to ```2``` which will create a 2d ```ndarray``` that is a row vector opposed to a 1d ```ndarray```:

In [143]:
row = np.array([1, 2, 3], ndmin=2)

In [144]:
row

array([[1, 2, 3]])

In [145]:
row.dtype

dtype('int32')

In [146]:
row.ndim

2

In [147]:
row.shape

(1, 3)

The transpose ```T``` attribute can be used to convert the row into a column:

In [148]:
col = row.T

In [149]:
col

array([[1],
       [2],
       [3]])

In [150]:
col.dtype

dtype('int32')

In [151]:
col.ndim

2

In [152]:
col.shape

(3, 1)

The 1d array or *1d vector* has a single dimension that spans over n columns (in this case n=3):

In [134]:
one_d.shape

(3,)

The 2d array or *2d row vector*, has 1 row and n columns (in this case n=3):

In [135]:
row.shape

(1, 3)

The 2d array or *2d col vector*, has n rows and 1 column (in this case n=3):

In [136]:
col.shape

(3, 1)

If the following are compared:

In [137]:
one_d.shape

(3,)

In [138]:
row.shape

(1, 3)

The ```shape``` is a ```tuple``` containing dimensions. 

Notice that the new dimension is left appended; the origin of this new dimension is the length of the outer ```list```. The next element is the dimension of a nested ```list``` instance:

In [141]:
len([[1, 2, 3]])

1

In [142]:
len([1, 2, 3])

3

The datatype ```dtype``` can be specified:

In [153]:
rowf = np.array([1, 2, 3], dtype=float, ndmin=2)

Now all the numeric values can be seen to be ```float``` instances:

In [154]:
rowf

array([[1., 2., 3.]])

This can be confirmed by examining the ```dtype``` attribute:

In [159]:
rowf.dtype

dtype('float64')

When the datatype ```dtype``` of an array is set to the ```builtins.int```, ```builtins.float```, or ```builtins.complex``` classes, the equivalent ```numpy``` classes ```np.int32```, ```np.float64``` or ```complex128``` are selected:

In [162]:
np.int32

numpy.int32

In [160]:
np.float64

numpy.float64

In [161]:
np.complex128

numpy.complex128

These have the alias ```np.int_```, ```np.float_```, and ```np.complex_```:

In [166]:
np.int_ == np.int32

True

In [167]:
np.float_ == np.float64

True

In [168]:
np.complex_ == np.complex128

True

The docstring also includes details about other factory functions to create an ```ndarray```:

|factory function|description|
|---|---|
|empty_like|Return an empty array with shape and type of input.|
|ones_like|Return an array of ones with shape and type of input.|
|zeros_like|Return an array of zeros with shape and type of input.|
|full_like|Return a new array with shape of input filled with value.|
|empty| Return a new uninitialized array.|
|ones|Return a new array setting values to one.|
|zeros|Return a new array setting values to zero.|
|full|Return a new array of given shape filled with value.|

Supposing the following matrix ```mat1``` is constructed:

In [173]:
mat1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

This has 2 dimensions:

In [176]:
mat1.ndim

2

2 rows by columns:

In [175]:
mat1.shape

(2, 3)

And 6 elements:

In [174]:
mat1.size

6

The other factory functions ```empty_like```, ```ones_like```, ```zeros_like``` and ```fulls_like``` can be used on this prototype array.

The ```empty_like``` uses the input argument ```prototype``` and all the values are initialised using junk values:

In [177]:
mat2 = np.empty_like(prototype=mat1)
mat2

array([[         0, 1072693248,          0],
       [1073741824,          0, 1074266112]])

The ```ones_like```, ```zeros_like``` and ```fulls_like``` use the input argument ```a``` (for array) and ```fulls_like``` requires an additional input argument ```full_value```:

In [179]:
mat3 = np.zeros_like(a=mat1)
mat3

array([[0, 0, 0],
       [0, 0, 0]])

In [180]:
mat4 = np.ones_like(a=mat1)
mat4

array([[1, 1, 1],
       [1, 1, 1]])

In [182]:
mat5 = np.full_like(a=mat1, fill_value=2)
mat5

array([[2, 2, 2],
       [2, 2, 2]])

```empty```, ```zeros```, ```ones``` and ```full``` cand be used to instead create an equivalent matrix from a ```shape```, which is a ```tuple``` of dimensions:

In [184]:
mat6 = np.empty(shape=(4, 3))
mat6

array([[1.01855798e-312, 1.08221785e-312, 1.03977794e-312],
       [9.54898106e-313, 1.01855798e-312, 1.03977794e-312],
       [1.23075756e-312, 1.01855798e-312, 1.10343781e-312],
       [9.76118064e-313, 1.01855798e-312, 1.90979621e-312]])

In [186]:
mat7 = np.zeros(shape=(2, 1))
mat7

array([[0.],
       [0.]])

In [188]:
mat7 = np.ones(shape=(2, 2))
mat7

array([[1., 1.],
       [1., 1.]])

In [189]:
mat8 = np.full(shape=(5, 1), fill_value=4)
mat8

array([[4],
       [4],
       [4],
       [4],
       [4]])

Notice that the datatype ```dtype``` for ```empty```, ```zero```, ```ones``` is ```float``` (```np.float64```) by default but can be overridden with the ```dtype``` keyword input argument:

In [190]:
mat9 = np.ones(shape=(4, 3), dtype=int)
mat9

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

The ```dtype``` for the ```array``` constructed using the ```full``` function is inferred by the ```fill_value``` but can be changed from the default.

It is possible to construct higher dimension arrays, however it becomes difficult to visualise arrays that have a higher dimension than the computer screen. For this reason it is worthwhile conceptualising some physical objects:

|ndim|description|shape|
|---|---|---|
|1|line vector|(c, )|
|2|page consisting of rows of equal length line vectors|(r, c)|
|3|book of equally sized pages|(b, r, c)|
|4|shelf of equally sized books|(s, b, r, c)|
|5|wardrobe of equally sized shelves|(w, s, b, r, c)|
|6|library of equally sized wardrobes|(l, w, s, b, r, c)|
|7|group of equally sized libraries|(g, l, w, s, b, r, c)|

A book can therefore be constructed from a ```list```, of nested ```list``` instances, of nested ```list``` instances, spacing is normally used to seperate the matrices corresponding to each page:

In [191]:
book1 = np.array([[[1, 2,], 
                   [3, 4]],
                  
                  [[5, 6], 
                   [7, 8]],
                  
                  [[9, 10], 
                   [11, 12]]])

In [192]:
book1

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

This book has 3 dimensions:

In [194]:
book1.ndim

3

With a total of 12 elements:

In [193]:
book1.size

12

And a shape of 3 pages, by 2 rows by 2 columns:

In [195]:
book1.shape

(3, 2, 2)

## ravel and reshape

An array has the attributes ```size```, ```ndim``` and ```shape```. The dimensionality of an array is ignored when the array is cast into an iterator using the ```flat``` attribute. Recall an iterator has no dimensionality because it only displays a single value at a time:

In [211]:
it = book1.flat
it

The value of the iterator can be advanced using ```next```:

In [197]:
next(it)

1

In [198]:
next(it)

2

Alternatively it can be cast into a ```list``` using:

In [199]:
list(it) # remaining elements

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

Notice that the array is deconstructed in row order, meaning each consecutive row is essentially concentenated. This can be seen by consuming the iterator by casting it to a ```list```. 

In [200]:
book1

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [201]:
list(book1.flat)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

The function ```np.ravel``` and the immutable method ```ndarray.ravel``` will instead unravel all the elements and ravel them in a 1d ```ndarray```:

In [214]:
np.ravel(book1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [213]:
book1.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

The ```numpy``` function and ```ndarray``` method ```ravel``` have the keyword input argument ```order```. The ```order``` is assigned to a string that is ```'C'``` (default) or ```'F'``` which stand for the C (row-major) and Fortran (column-major) programming languages respectively. **Do not confuse C with column.**

In [217]:
book1.ravel(order='C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [218]:
book1.ravel(order='F')

array([ 1,  5,  9,  3,  7, 11,  2,  6, 10,  4,  8, 12])

Comparison of the 2 unravelled arrays shows that it is far more logical to use the default ```'C'``` (row-order).

The ```builtins``` class ```list``` can be used to cast the outer layer of an ```ndarray``` to a ```list```. Notice that this is a ```list``` of nested ```ndarray``` instances:

In [215]:
list(book1)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

The mutatable method ```ndarray.tolist``` will instead cast the ```ndarray``` into a ```list``` of nested ```list``` of nested ```list``` instances:

In [216]:
book1.tolist()

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

An ```ndarray``` can also be reshaped to new dimensions, providing that the ```size``` of the new dimensions matches the ```size``` of the original dimensions. The original ```ndarray``` is essentially ravelled and each element is then used to populate the new dimensions. 

Once again there is the funtion ```np.reshape``` and the immutatable method ```np.reshape```:

In [68]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [ ]:
np.ndarray(shape=(3, 3), 
           dtype=int, 
           buffer=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))